# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
